name: build and push
on:
  workflow_run:
    workflows: [ "test-backend" ]
    types: [ completed ]

jobs:
  build-and-push-docker-image:
      needs: test-backend
      if: github.event.workflow_run.head_branch == 'main'
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
            cache: 'maven'

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

        - name: Build image and push backend
          uses: docker/build-push-action@v6
          with:
            context: ./simple-api
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKER_USERNAME }}/tp1_devops-backend:latest

        - name: Build image and push database
          uses: docker/build-push-action@v6
          with:
            context: ./TPDocker
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKER_USERNAME }}/tp1_devops-database:latest

        - name: Build image and push httpd
          uses: docker/build-push-action@v6
          with:
            context: ./httpd
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKER_USERNAME }}/tp1_devops-httpd:latest

        - name: sonarCloud analysis
          run: mvn -B verify sonar:sonar -Dsonar.projectKey=folnab_TP_DevOps -Dsonar.organization=folnab -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml