name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'

      #finally build your app with the latest command
      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn -B clean verify
        
  build-and-push-docker-image:
      needs: test-backend
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

        - name: Build image and push backend
          uses: docker/build-push-action@v6
          with:
            context: ./simple-api
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1_devops-backend:latest

        - name: Build image and push database
          uses: docker/build-push-action@v6
          with:
            context: ./TPDocker
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1_devops-database:latest

        - name: Build image and push httpd
          uses: docker/build-push-action@v6
          with:
            context: ./httpd
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp1_devops-httpd:latest
